---
- name: add sury.org apt key
  ansible.builtin.get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /usr/share/keyrings/deb.sury.org-php.gpg
   
- name: add sury.org repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: install php7.4
  apt:
    name:
      - libapache2-mod-php7.4
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-mysql
    cache_valid_time: "{{ apt_cache_valid_time }}"
    update_cache: yes
  notify: restart apache2